# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name' : 'Hospital Management',
    'version' : '1.0',
    'summary': 'Hospital management Software',
    'sequence': 10,
    'description': """Hospital Management Software""",
    'category': 'Productivity',
    'website': 'https://www.odoo.com/page/productivity',
    'depends' : ['base','sale','mail', 'report_xlsx', 'web_progress'],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'wizard/create_appointment_wizard_view.xml',
        'wizard/search_appointment_wizard_view.xml',
        'wizard/appointment_report_view.xml',
        'wizard/all_patient_report_view.xml',
        'wizard/loading_appointment.xml',
        'views/patient_view.xml',
        'views/doctor_view.xml',
        'views/appointment_view.xml',
        'views/kids_view.xml',
        'views/patient_gender_view.xml',
        'views/sale.xml',
        'views/order_move.xml',
        'report/report.xml',
        'report/patient_details_template.xml',
        'report/patient_card.xml',
        'report/appointment_details.xml',
        'report/all_patient_list.xml',
        'report/sale_report_inherit.xml',
        'views/menu.xml',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}